local LuckyBlocks = {}

LuckyBlocks.Data = {
    CommonLuckyBlock = {
        DisplayName = "Lucky Block",
        Rarity = "Common",
        
        Image = "rbxassetid://133495849637215",

        MinLevel = 1,
        MaxLevel = 10,

        Blacklist = {},
    },
    RareLuckyBlock = {
        DisplayName = "Lucky Block",
        Rarity = "Rare",
        
        Image = "rbxassetid://89530799088867",

        MinLevel = 10,
        MaxLevel = 20,

        Blacklist = {},
    },
    EpicLuckyBlock = {
        DisplayName = "Lucky Block",
        Rarity = "Epic",
        
        Image = "rbxassetid://89530799088867",

        MinLevel = 20,
        MaxLevel = 30,

        Blacklist = {},
    },
    LegendaryLuckyBlock = {
        DisplayName = "Lucky Block",
        Rarity = "Legendary",
        
        Image = "rbxassetid://89530799088867",

        MinLevel = 30,
        MaxLevel = 40,
    },
    MythicalLuckyBlock = {
        DisplayName = "Lucky Block",
        Rarity = "Mythical",
        
        Image = "rbxassetid://89530799088867",

        MinLevel = 40,
        MaxLevel = 50,
    },
    SecretLuckyBlock = {
        DisplayName = "Lucky Block",
        Rarity = "Secret",
        
        Image = "rbxassetid://89530799088867",

        MinLevel = 50,
        MaxLevel = 60,
    },
    DivineLuckyBlock = {
        DisplayName = "Lucky Block",
        Rarity = "Divine",
        
        Image = "rbxassetid://89530799088867",

        MinLevel = 60,
        MaxLevel = 70,
    },
    SuperiorLuckyBlock = {
        DisplayName = "Lucky Block",
        Rarity = "Superior",
        
        Image = "rbxassetid://89530799088867",

        MinLevel = 70,
        MaxLevel = 80,
    },
}

return LuckyBlocks