local Shared_Sounds = {}

Shared_Sounds.SFX = {
	Success = "rbxassetid://136993031050456",
	Error = "rbxassetid://128635936514965",
	UiPop = "rbxassetid://140515349341063",
	ImageButtonClick = "rbxassetid://135366639238389",
	CashAdd = "rbxassetid://134583420216867",
	CashCollect = "rbxassetid://114703843022722",
	CashPopupAppear = "rbxassetid://134637530898931",
	ProximityActivate = "rbxassetid://132673746791429",
}

Shared_Sounds.SFXVolume = {
	ImageButtonClick = 1.25,
	Success = 0.65,
	Error = 0.65,
	CashCollect = 0.5,
}

Shared_Sounds.Music = {
	Background = "rbxassetid://136703374512384",
}

return Shared_Sounds
