local Shared_SixSevenReward = {}

Shared_SixSevenReward.GroupId = 32638698
Shared_SixSevenReward.LuckyBlockConfigName = "SixSevenLuckyBlock"
Shared_SixSevenReward.ClaimWaitSeconds = 15
Shared_SixSevenReward.ServerResponseGraceSeconds = 5

Shared_SixSevenReward.JoinMessage = "Join the Group!"
Shared_SixSevenReward.SuccessMessage = "Thank you! Enjoy 67 Lucky Block!"
Shared_SixSevenReward.TimeoutMessage = "Join the group within 15 seconds to claim your 67 Lucky Block!"
Shared_SixSevenReward.NotInGroupMessage = "You must join the group to claim your 67 Lucky Block!"
Shared_SixSevenReward.AlreadyClaimedMessage = "You already claimed your 67 Lucky Block!"

return Shared_SixSevenReward
